// <auto-generated />
using System;
using Gold.Vikings.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HydroService.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Gold.Vikings.Models.Boat", b =>
                {
                    b.Property<int>("BoatId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BoatActive");

                    b.Property<string>("BoatComment");

                    b.Property<string>("BoatName");

                    b.Property<string>("BoatNumber");

                    b.HasKey("BoatId");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("Gold.Vikings.Models.BoatSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoatId");

                    b.Property<string>("ScheduleComment");

                    b.Property<DateTime>("TimeEnd");

                    b.Property<DateTime>("TimeStart");

                    b.HasKey("ScheduleId");

                    b.HasIndex("BoatId");

                    b.ToTable("BoatSchedules");
                });

            modelBuilder.Entity("Gold.Vikings.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientName");

                    b.Property<string>("ClientPhone");

                    b.Property<DateTime>("ClientRegistred");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Gold.Vikings.Models.DayShedule", b =>
                {
                    b.Property<int>("DaySheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BoatActive");

                    b.Property<string>("BoatComment");

                    b.Property<int>("BoatId");

                    b.Property<string>("BoatName");

                    b.Property<string>("BoatNumber");

                    b.Property<int?>("ClientId");

                    b.Property<string>("ScheduleComment");

                    b.Property<int>("ScheduleId");

                    b.Property<DateTime>("TimeEnd");

                    b.Property<DateTime>("TimeStart");

                    b.HasKey("DaySheduleId");

                    b.HasIndex("ClientId");

                    b.ToTable("DayShedules");
                });

            modelBuilder.Entity("Gold.Vikings.Models.BoatSchedule", b =>
                {
                    b.HasOne("Gold.Vikings.Models.Boat", "Boat")
                        .WithMany("BoatSchedule")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gold.Vikings.Models.DayShedule", b =>
                {
                    b.HasOne("Gold.Vikings.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
